### ISSUE TITLE
Concluding message for text sign-up

### ISSUE THREAD

**Issue by smarziano** [smartchicago/kimball#106]
When a user completes the sign-up process via text message, we should have a message that gives them a few more details. 

If the user prefers email, the message should read:
_You are now signed up for CUTGroup! Your $5 gift card will be in the mail. When new tests come up, you’ll receive an email from smarziano@cct.org with details._

If the user prefers text, the message should read:
_You are now signed up for CUTGroup! Your $5 gift card will be in the mail. When new tests come up, you’ll receive a text from ###-###-#### with more details._

@shua123 -- will the phone number be the same for text sign-up and notifications?

**Comment by smarziano** [comment]
@shua123 New phone number for live text messaging is 773-747-6239

**Comment by shua123** [comment]
This is implemented on staging. It was spilling over into multiple text messages but that could just be my phone being weird. @smarziano

**Comment by shua123** [comment]
The apostrophe that had been copy-pasted into the code caused messages to split into 3 parts due to a unicode character issue. More at https://www.twilio.com/help/faq/sms/why-are-my-messages-with-unicode-being-split

Replacing apostrophes in the first wufoo question text and the ending message in commit https://github.com/smartchicago/kimball/commit/faea7fb5d2049554daf3bad49f456237d453ea84 fixes issue.

**Comment by shua123** [comment]
Deployed!
