### ISSUE TITLE
Send text message to group of people

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#113]
Send a text message to a subset of users. Some possibilities:
  * Ability to take users from Search results
  * Maybe some common subsets? 
 
This is generic functionality. It could be used to kick off the process for #112 or a one time message.

**Comment by smarziano** [comment]
After segmenting the group to the testers we want to invite, these are the key parts of the initial call-out text message(s) that are required:
- "New CUTGroup Test Opportunity..." or "Make $20 at our next CUTGroup test of..."
- Type of test (in-person/remote)
- Kind of website/app/tech being tested (example: transportation website, neighborhood info app, schools website, etc)
- Date & time
- Call to action: Please text back [KEYWORD] if you are interested in this test.

@shua123 I will craft some example messages from old tests to give examples. Ideally, I would like to keep this to 2 messages (3 at the very most).

**Comment by smarziano** [comment]
In addition, we need to think about informing testers about approximate time-frame when they should hear back since the expectation with text messaging is that responses are more immediate.

**Comment by smarziano** [comment]
@shua123 Here is an example of how we would translate the emails to text messages:
https://docs.google.com/document/d/1OItRTQpv2d6COjC73iWES3tgLHjj35sTKJs28RHKLoU/edit

Once a tester submits the time slot they want we need to discuss how exactly we want to end the conversation. Do we confirm immediately? Can we have a limited amount of responses for each time slot? We normally do this via Wufoo form, and when a time slot is full I change the form to reflect that. 

In the email conversation, we let testers know that we will write back to confirm their time slot since we ask them to tell us all times when they are available.

**Comment by smarziano** [comment]
Closing this issue since we have an opportunity to write a custom end message after all of the questions have been submitted. In this message we can say how long it will take before the testers hear back. We are not going to limit the number of responses per time slot but will need to look into how we ask testers about their availability for a time slot.
