### ISSUE TITLE
Associate outgoing text message with twilio-wufoo connection

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#127]
Associate outgoing text messages (through search and import) to a twilio-wufoo connection. Add section to Person profile to display messages sent to them.

**Comment by shua123** [comment]
Put list of outgoing messages under a Communications section

**Comment by smarziano** [comment]
In the future we will think about how the campaigns + responses are organized... probably by test. Therefore it would show which tests a tester was invited to and if they responded and if so how they responded for the screening questions.

**Comment by shua123** [comment]
Outgoing messages through search and import are saving with a Twilio-Wufoo Connection (now called SMS Campaign) ID. https://github.com/smartchicago/kimball/commit/82165cef9725b23de69d6abfda02464ac2997a30

**Comment by smarziano** [comment]
Instead of listing all of the messages that a tester receives on the profile page, let's just list the name of the SMS campaign.

**Comment by smarziano** [comment]
SMS outgoing messages are now associated with a Twilio-Wufoo connection and is showing up on the tester profile page. In the future, we want to incorporate these communications (as well as email communications) in the audit log #131. 

Closing for now since we can keep track of the SMS messages testers receive.
