### ISSUE TITLE
Gift Card Type/reasons

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#175]
Categories or reasons for giving a gift card:

1. Sign up
2. Completing a test (event?)
3. Refer-a-friend
4. Other(?)

@smarziano @cromulus additions?

**Comment by cromulus** [comment]
5. submission

for us, I'd add 6: interview

**Comment by smarziano** [comment]
This is currently the list of reasons on staging:
<img width="219" alt="screen shot 2016-07-25 at 10 48 46 am" src="https://cloud.githubusercontent.com/assets/5550969/17107566/6b6d2806-5255-11e6-9238-818c013cd951.png">

A couple of notes:
- "Reason" should not be a selectable option
- "Unknown" should also not be an option because we have to know why we're giving someone gift card.
- Can we create a way to write what "Other" is by adding single text field?
- Instead of having both "Test" and "Interview" maybe we should just use "Event" so it's useful to all groups? I am open to keeping both of them.

**Comment by smarziano** [comment]
Next steps based on our discussion today:
- [ ] Remove "unknown" as an option
- [ ] Remove "Interview" as an option 
- [ ] This is such a small detail, but please capitalize each reason
- [ ] Show notes field if "Other" is selected

**Comment by smarziano** [comment]
All of the tasks have been completed. Closing issue.
